# Generated by Django 5.1.3 on 2025-12-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioWeb',
            fields=[
                ('id_formweb', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_formweb', models.CharField(max_length=100)),
                ('email_formweb', models.EmailField(max_length=254)),
                ('tlfno_formweb', models.CharField(max_length=10)),
                ('nomempre_formweb', models.CharField(max_length=250)),
                ('servicio_formweb', models.CharField(max_length=250)),
                ('mensaje_formweb', models.TextField()),
                ('fecha_formweb', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'FormularioWeb',
                'managed': False,
            },
        ),
    ]
