# Generated by Django 4.2.9 on 2026-01-21 21:08

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('PaginaW', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraAcciones',
            fields=[
                ('id_bita', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=100)),
                ('modulo', models.CharField(max_length=50)),
                ('regist_modif', models.IntegerField()),
                ('valor_anter', models.JSONField(blank=True, null=True)),
                ('valor_nuevo', models.JSONField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'BitacoraAcciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id_cond', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_cond', models.CharField(max_length=150)),
                ('apell_cond', models.CharField(max_length=150)),
                ('cedla_cond', models.CharField(max_length=150, unique=True)),
                ('tipolicen_cond', models.CharField(max_length=3)),
                ('telfno_cond', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'Conductor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionMantenimiento',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_trabajo', models.CharField(max_length=250)),
                ('kilome_intervalo', models.IntegerField()),
            ],
            options={
                'db_table': 'ConfiguracionMantenimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleManTrailer',
            fields=[
                ('id_detamantrai', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'DetalleManTrailer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InsumoDetalleTrailer',
            fields=[
                ('id_insumotrai', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_insumo', models.CharField(max_length=250)),
                ('cantidad', models.IntegerField()),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'InsumoDetalleTrailer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MantenimientoTrailer',
            fields=[
                ('id_mantrai', models.AutoField(primary_key=True, serialize=False)),
                ('kilometraje', models.IntegerField()),
                ('fecha_mantrai', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'MantenimientoTrailer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarcaTrailer',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'MarcaTrailer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id_trai', models.AutoField(primary_key=True, serialize=False)),
                ('placa_trai', models.CharField(max_length=8, unique=True)),
                ('anio_trai', models.IntegerField()),
                ('numotor_trai', models.CharField(max_length=50, unique=True)),
                ('numchasis_trai', models.CharField(max_length=50, unique=True)),
                ('numdisco_trai', models.CharField(max_length=5)),
                ('kilometraje_actual', models.IntegerField()),
                ('fechcaduc_trai', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Trailer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin', 'Administrador'), ('conductor', 'Conductor')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, related_name='usuarios', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuarios_permisos', to='auth.permission')),
            ],
            options={
                'db_table': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
