# Generated by Django 4.2.9 on 2026-02-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaW', '0002_bitacoraacciones_conductor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoRecuperacion',
            fields=[
                ('id_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=6)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('valido_hasta', models.DateTimeField()),
            ],
            options={
                'db_table': 'codigorecuperacion',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='conductor',
            table='conductor',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
